from scipy.sparse import load_npz

import numpy as np
import csv
import os
import datetime


def _load_csv(path):
    # A helper function to load the csv file.
    if not os.path.exists(path):
        raise Exception("The specified path {} does not exist.".format(path))
    # Initialize the data.
    data = {
        "user_id": [],
        "question_id": [],
        "is_correct": []
    }
    # Iterate over the row to fill in the data.
    with open(path, "r") as csv_file:
        reader = csv.reader(csv_file)
        for row in reader:
            try:
                data["question_id"].append(int(row[0]))
                data["user_id"].append(int(row[1]))
                data["is_correct"].append(int(row[2]))
            except ValueError:
                # Pass first row.
                pass
            except IndexError:
                # is_correct might not be available.
                pass
    return data


def _load_student_csv(path):
    # A helper function to load the csv file.
    if not os.path.exists(path):
        raise Exception("The specified path {} does not exist.".format(path))
    # Initialize the data.
    data = {
    }
    # Iterate over the row to fill in the data.
    with open(path, "r") as csv_file:
        reader = csv.reader(csv_file)
        next(reader, None)
        for row in reader:
            try:
                if row[2].strip():
                    dob = datetime.datetime.strptime(row[2], "%Y-%m-%d %H:%M:%S.%f")
                    current_date = datetime.datetime.now()
                    age = current_date.year - dob.year - ((current_date.month, current_date.day) < (dob.month, dob.day))
                else:
                    age = -1

                data[int(row[0])] = age
            except ValueError:
                # Pass first row.
                pass
            except IndexError:
                # is_correct might not be available.
                pass
    return data


def category_subjects(name):
    # KEYWORDS ARE GENERATED BY GPT-4
    k_map = {
        0: {"arithmetic", "decimal", "factor", "multiple", "prime", "roman", "number",
            "rounding", "converting", "fraction", "percentage", "ratio", "surd", "index",
            "power", "root", "negative", "simplifying"},
        1: {"algebra", "bracket", "equation", "formula", "expression", "expand",
            "factorise", "quadratic", "linear", "simultaneous", "rearrange", "square", "algebraic"},
        2: {"geometry", "angle", "area", "pythagoras", "volume", "surface", "shape", "3d", "coordinate",
            "symmetry", "congruency", "perimeter", "bearing", "circle", "theorem", "polygon", "quadrilateral",
            "construction", "loci"},
        3: {"graph", "function", "linear", "quadratic", "trigonometric", "cubic", "reciprocal",
            "real life", "inequality", "sequence", "plot", "transformation", "axis"},
        4: {"statistic", "probability", "average", "data", "scatter", "range", "frequency", "pie",
            "histogram", "box", "cumulative", "bar", "experimental", "tree", "sampling", "bias", "stem",
            "leaf", "series", "two way"},
        5: {"advanced", "pure", "differentiate", "integrate", "matrix", "modulus", "series", "trigonometry",
            "vector", "exponential", "logarithm", "sequence", "calculus"},
        6: {"money", "calculator", "speed", "distance", "time", "practical", "real life", "measurement",
            "unit", "scale", "estimate", "application", "density", "pressure", "force", "motion"},
        7: {"basic", "mental", "written", "addition", "subtraction", "multiplication", "division",
            "count", "place value", "order", "operation", "tally", "chart"},
        8: {"method", "technique", "strategy", "listing", "systematic", "solve", "approach",
            "problem solve", "methodical"}}

    lower_name = name.lower()
    for key, value in k_map.items():
        for keyword in value:
            if keyword in lower_name:
                return key

    return 9


def _load_question_csv(path):
    # A helper function to load the csv file.
    if not os.path.exists(path):
        raise Exception("The specified path {} does not exist.".format(path))
    # Initialize the data.
    data = {
    }
    # Iterate over the row to fill in the data.
    with open(path, "r") as csv_file:
        reader = csv.reader(csv_file)
        next(reader, None)
        for row in reader:
            try:
                category = category_subjects(str(row[1]))

                data[int(row[0])] = category
            except ValueError:
                # Pass first row.
                pass
            except IndexError:
                # is_correct might not be available.
                pass
    return data


def load_train_sparse(root_dir="/data"):
    """ Load the training data as a spare matrix representation.

    :param root_dir: str
    :return: 2D sparse matrix
    """
    path = os.path.join(root_dir, "train_sparse.npz")
    if not os.path.exists(path):
        raise Exception("The specified path {} "
                        "does not exist.".format(os.path.abspath(path)))
    matrix = load_npz(path)
    return matrix


def load_train_csv(root_dir="/data"):
    """ Load the training data as a dictionary.

    :param root_dir: str
    :return: A dictionary {user_id: list, question_id: list, is_correct: list}
        WHERE
        user_id: a list of user id.
        question_id: a list of question id.
        is_correct: a list of binary value indicating the correctness of
        (user_id, question_id) pair.
    """
    path = os.path.join(root_dir, "train_data.csv")
    return _load_csv(path)


def load_valid_csv(root_dir="/data"):
    """ Load the validation data as a dictionary.

    :param root_dir: str
    :return: A dictionary {user_id: list, question_id: list, is_correct: list}
        WHERE
        user_id: a list of user id.
        question_id: a list of question id.
        is_correct: a list of binary value indicating the correctness of
        (user_id, question_id) pair.
    """
    path = os.path.join(root_dir, "valid_data.csv")
    return _load_csv(path)


def load_student_meta_csv(root_dir="/data"):
    """ Load the student data as a dictionary.

    :param root_dir: str
    """
    path = os.path.join(root_dir, "student_meta.csv")
    return _load_student_csv(path)


def load_subject_meta_csv(root_dir="/data"):
    """ Load the subject data as a dictionary.

    :param root_dir: str
    """
    path = os.path.join(root_dir, "subject_meta.csv")
    return _load_question_csv(path)


def load_public_test_csv(root_dir="/data"):
    """ Load the test data as a dictionary.

    :param root_dir: str
    :return: A dictionary {user_id: list, question_id: list, is_correct: list}
        WHERE
        user_id: a list of user id.
        question_id: a list of question id.
        is_correct: a list of binary value indicating the correctness of
        (user_id, question_id) pair.
    """
    path = os.path.join(root_dir, "test_data.csv")
    return _load_csv(path)


def load_private_test_csv(root_dir="/data"):
    """ Load the private test data as a dictionary.

    :param root_dir: str
    :return: A dictionary {user_id: list, question_id: list, is_correct: list}
        WHERE
        user_id: a list of user id.
        question_id: a list of question id.
        is_correct: an empty list.
    """
    path = os.path.join(root_dir, "private_test_data.csv")
    return _load_csv(path)


def save_private_test_csv(data, file_name="private_test_result.csv"):
    """ Save the private test data as a csv file.

    This should be your submission file to Kaggle.
    :param data: A dictionary {user_id: list, question_id: list, is_correct: list}
        WHERE
        user_id: a list of user id.
        question_id: a list of question id.
        is_correct: a list of binary value indicating the correctness of
        (user_id, question_id) pair.
    :param file_name: str
    :return: None
    """
    if not isinstance(data, dict):
        raise Exception("Data must be a dictionary.")
    cur_id = 1
    valid_id = ["0", "1"]
    with open(file_name, "w") as csv_file:
        writer = csv.writer(csv_file)
        writer.writerow(["id", "is_correct"])
        for i in range(len(data["user_id"])):
            if str(int(data["is_correct"][i])) not in valid_id:
                raise Exception("Your data['is_correct'] is not in a valid format.")
            writer.writerow([str(cur_id), str(int(data["is_correct"][i]))])
            cur_id += 1
    return


def evaluate(data, predictions, threshold=0.5):
    """ Return the accuracy of the predictions given the data.

    :param data: A dictionary {user_id: list, question_id: list, is_correct: list}
    :param predictions: list
    :param threshold: float
    :return: float
    """
    if len(data["is_correct"]) != len(predictions):
        raise Exception("Mismatch of dimensions between data and prediction.")
    if isinstance(predictions, list):
        predictions = np.array(predictions).astype(np.float64)
    return (np.sum((predictions >= threshold) == data["is_correct"])
            / float(len(data["is_correct"])))


def sparse_matrix_evaluate(data, matrix, threshold=0.5):
    """ Given the sparse matrix represent, return the accuracy of the prediction on data.

    :param data: A dictionary {user_id: list, question_id: list, is_correct: list}
    :param matrix: 2D matrix
    :param threshold: float
    :return: float
    """
    total_prediction = 0
    total_accurate = 0
    for i in range(len(data["is_correct"])):
        cur_user_id = data["user_id"][i]
        cur_question_id = data["question_id"][i]
        if matrix[cur_user_id, cur_question_id] >= threshold and data["is_correct"][i]:
            total_accurate += 1
        if matrix[cur_user_id, cur_question_id] < threshold and not data["is_correct"][i]:
            total_accurate += 1
        total_prediction += 1
    return total_accurate / float(total_prediction)


def sparse_matrix_predictions(data, matrix, threshold=0.5):
    """ Given the sparse matrix represent, return the predictions.

    This function can be used for submitting Kaggle competition.

    :param data: A dictionary {user_id: list, question_id: list, is_correct: list}
    :param matrix: 2D matrix
    :param threshold: float
    :return: list
    """
    predictions = []
    for i in range(len(data["user_id"])):
        cur_user_id = data["user_id"][i]
        cur_question_id = data["question_id"][i]
        if matrix[cur_user_id, cur_question_id] >= threshold:
            predictions.append(1.)
        else:
            predictions.append(0.)
    return predictions
